### ISSUE TITLE
No License in repo

### ISSUE THREAD

**Issue by bprox** [Ishan333/STC#1]
Hey @Ishan333 

I have been using your STC for some time now and love it! I am starting to create different projects for my own development experience. I know your code is available but I would not feel comfortable using it (even as reference) unless there is a license in this repo.

Would it be possible for you to add an open-source license to your repo so I may use your code if need be?

brent

**Comment by Meshuggah333** [comment]
Hey @natkingcoleslaw 
I'm sorry it took so long to answer you, that github notification got stuck in a filter of my mail account.
I can't slap a license on this thing as I used Dave McMullen's code which is both very old and public domain.
So consider my version of his work to be the same.
You should be aware the calculations done aren't very accurate anymore (if they ever were), as the weight datas for both D'Addario and CircleK (now Kalium Strings) have certainly evolved.
Have fun with the code, I'll check out what you did with it :)

**Comment by bprox** [comment]
Hey @Ishan333

Thanks for getting back to me. I will be updating the string data and taking a closer look at the formula for calculating the tensions as I have seen a few different ways to do it but not sure which to use yet. 

I'm using your (and D. McMullen's) code as a basis since I like the way the code/logic is written. I'm currently prototyping it in python (for learning purposes) and then hopefully throwing it in a chrome app. I'm on sevenstring.org (bpprox22) so when it's finished I'll be sure to let you know! Thanks again
